### ISSUE TITLE
[BUG] HDRP 10.2.2 SafePositivePow_half is already defined

### ISSUE THREAD

**Issue by melMass** [alelievr/Mixture#21] opened 2020-12-19 17:56 UTC
**Describe the bug**
In FinalCopy.shader, the template is now already defined in HDRP 10.2.2

But looking at the code in the repo it is very different from the one on openUPM do you plan to update it?

**Comment by alelievr** [comment] 2020-12-20 19:06
Hello,

I already see this error but I'm not really sure what's the cause. I'll need to investigate a bit before I can find a fix.

FYI I'll make a new release on openUpm soon, I just need to fix another issue before (and this one).

**Comment by alelievr** [comment] 2020-12-22 18:16
So, this bug should be fixed with this commit: https://github.com/alelievr/Mixture/commit/95c4f7e6b4b75e2964af10047f5b329e038f4b01 (it removes every bit of CGPROGRAM I had, which was causing issues with Common.hlsl in the core package)

I published version 0.0.5 that contains this fix, it will be available on OpenUPM in a couple of minutes

**Closed by alelievr** 2020-12-22 18:16 UTC
Labels: bug
